### ISSUE TITLE
Tidak ada respons setelah klik autorunningcmd.exe 

### ISSUE THREAD

**Issue by aldiock** [AnandaRauf/BotacsPro---Bot-Auto_Checkout-Flashsale-Shopee-Promo#3]
Padahal saya sudah setting semua sesuai dengan yang di tutorial, tapi tidak ada respons apa-apa

**Comment by rizkiakbar-melin01** [comment]
> Padahal saya sudah setting semua sesuai dengan yang di tutorial, tapi tidak ada respons apa-apa

sya juga ni bg:"(
